// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// fpop2DTransfer
List fpop2DTransfer(DataFrame df, double penalty, NumericVector vectWeight, bool testMode);
RcppExport SEXP _fpop2D_fpop2DTransfer(SEXP dfSEXP, SEXP penaltySEXP, SEXP vectWeightSEXP, SEXP testModeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< double >::type penalty(penaltySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vectWeight(vectWeightSEXP);
    Rcpp::traits::input_parameter< bool >::type testMode(testModeSEXP);
    rcpp_result_gen = Rcpp::wrap(fpop2DTransfer(df, penalty, vectWeight, testMode));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fpop2D_fpop2DTransfer", (DL_FUNC) &_fpop2D_fpop2DTransfer, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_fpop2D(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
