# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fpop2DTransfer <- function(df, penalty, vectWeight, testMode) {
    .Call(`_fpop2D_fpop2DTransfer`, df, penalty, vectWeight, testMode)
}

